spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/layui
    username: root
    password: admin
    type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
    cache: false
    encoding: UTF-8
mybatis:
  type-aliases-package: com.qust.entity
  mapper-locations: classpath:com/qust/mapper/*Mapper.xml
